[2025-02-24T10:10:49.515+0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-24T10:10:49.539+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: muse_dag.extract_crypto_data scheduled__2025-02-01T01:00:00+00:00 [queued]>
[2025-02-24T10:10:49.552+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: muse_dag.extract_crypto_data scheduled__2025-02-01T01:00:00+00:00 [queued]>
[2025-02-24T10:10:49.553+0800] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-02-24T10:10:49.605+0800] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): extract_crypto_data> on 2025-02-01 01:00:00+00:00
[2025-02-24T10:10:49.611+0800] {standard_task_runner.py:72} INFO - Started process 34500 to run task
[2025-02-24T10:10:49.614+0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'muse_dag', 'extract_crypto_data', 'scheduled__2025-02-01T01:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/muse_dag.py', '--cfg-path', '/tmp/tmpzu0throw']
[2025-02-24T10:10:49.618+0800] {standard_task_runner.py:105} INFO - Job 17: Subtask extract_crypto_data
[2025-02-24T10:10:49.736+0800] {task_command.py:467} INFO - Running <TaskInstance: muse_dag.extract_crypto_data scheduled__2025-02-01T01:00:00+00:00 [running]> on host LAPTOP-7NCGBFK9.
[2025-02-24T10:10:49.853+0800] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='laurence' AIRFLOW_CTX_DAG_ID='muse_dag' AIRFLOW_CTX_TASK_ID='extract_crypto_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-01T01:00:00+00:00'
[2025-02-24T10:10:49.855+0800] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-24T10:10:49.857+0800] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-24T10:10:49.858+0800] {logging_mixin.py:190} INFO - Current task name:extract_crypto_data state:running start_date:2025-02-24 02:10:49.541141+00:00
[2025-02-24T10:10:49.860+0800] {logging_mixin.py:190} INFO - Dag name:muse_dag and current dag run status:running
[2025-02-24T10:10:49.862+0800] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-24T10:10:49.869+0800] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-24T10:10:49.871+0800] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', '/mnt/c/Users/User/laurence/Muse_assessment/muse_env/bin/python3 /mnt/c/Users/User/laurence/Muse_assessment/src/extract_crypto.py']
[2025-02-24T10:10:49.877+0800] {subprocess.py:99} INFO - Output:
[2025-02-24T10:10:49.964+0800] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-24T10:10:49.968+0800] {process_utils.py:132} INFO - Sending 15 to group 34500. PIDs of all processes in the group: [34503, 34500]
[2025-02-24T10:10:49.969+0800] {process_utils.py:87} INFO - Sending the signal 15 to group 34500
[2025-02-24T10:10:49.970+0800] {taskinstance.py:3094} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-02-24T10:10:50.133+0800] {taskinstance.py:3095} ERROR - Stacktrace: 
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/__main__.py", line 62, in main
    args.func(args)
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 254, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 322, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/jobs/local_task_job_runner.py", line 171, in _execute
    self.task_runner.start()
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 55, in start
    self.process = self._start_by_fork()
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 763, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/operators/bash.py", line 257, in execute
    result = self._run_inline_command(bash_path=bash_path, env=env)
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/operators/bash.py", line 284, in _run_inline_command
    return self.subprocess_hook.run_command(
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/hooks/subprocess.py", line 104, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    self.log.error("Stacktrace: \n%s", "".join(traceback.format_stack()))

[2025-02-24T10:10:50.135+0800] {subprocess.py:117} INFO - Sending SIGTERM signal to process group
[2025-02-24T10:10:50.154+0800] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 763, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/operators/bash.py", line 257, in execute
    result = self._run_inline_command(bash_path=bash_path, env=env)
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/operators/bash.py", line 284, in _run_inline_command
    return self.subprocess_hook.run_command(
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/hooks/subprocess.py", line 104, in run_command
    for raw_line in iter(self.sub_process.stdout.readline, b""):
  File "/mnt/c/Users/User/laurence/Muse_assessment/muse_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3097, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-02-24T10:10:50.169+0800] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-24T10:10:50.171+0800] {logging_mixin.py:190} INFO - Task start:2025-02-24 02:10:49.541141+00:00 end:2025-02-24 02:10:50.169478+00:00 duration:0.628337
[2025-02-24T10:10:50.173+0800] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): extract_crypto_data> dag:<DAG: muse_dag> dagrun:<DagRun muse_dag @ 2025-02-01 01:00:00+00:00: scheduled__2025-02-01T01:00:00+00:00, state:running, queued_at: 2025-02-24 02:08:01.376032+00:00. externally triggered: False>
[2025-02-24T10:10:50.174+0800] {logging_mixin.py:190} INFO - Failure caused by Task received SIGTERM signal
[2025-02-24T10:10:50.177+0800] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=muse_dag, task_id=extract_crypto_data, run_id=scheduled__2025-02-01T01:00:00+00:00, execution_date=20250201T010000, start_date=20250224T021049, end_date=20250224T021050
[2025-02-24T10:10:50.292+0800] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-24T10:10:50.306+0800] {process_utils.py:80} INFO - Process psutil.Process(pid=34500, status='terminated', exitcode=2, started='10:10:49') (34500) terminated with exit code 2
[2025-02-24T10:10:50.311+0800] {process_utils.py:80} INFO - Process psutil.Process(pid=34503, status='terminated', started='10:10:49') (34503) terminated with exit code None
[2025-02-24T10:11:28.966+0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-24T10:11:28.996+0800] {taskinstance.py:2604} INFO - Dependencies not met for <TaskInstance: muse_dag.extract_crypto_data scheduled__2025-02-01T01:00:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2025-02-24T10:11:29.000+0800] {local_task_job_runner.py:166} INFO - Task is not able to be run
